/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { UUPSBoxV1__factory } from "./UUPSBoxV1__factory";
export { UUPSBoxV2__factory } from "./UUPSBoxV2__factory";
