import { ethers } from "ethers";
import * as dotenv from "dotenv";
import * as fs from "fs";
import * as path from "path";

dotenv.config();

/**
 * Deployment script using ethers.js directly (no Hardhat)
 * 
 * This is a generic approach that works anywhere:
 * - Uses ethers.js Provider and Wallet directly
 * - Reads compiled contract artifacts from Foundry or solc
 * - No framework dependencies
 */
async function main() {
  console.log("=".repeat(60));
  console.log("Deploying Upgradeable Contract with Custom Proxy");
  console.log("Using: ethers.js directly (no Hardhat)");
  console.log("=".repeat(60));

  // Setup provider and wallet
  const rpcUrl = process.env.POLKADOT_TEST_HUB_RPC || "http://127.0.0.1:8545";
  const privateKey = process.env.PRIVATE_KEY;
  
  if (!privateKey) {
    throw new Error("PRIVATE_KEY not set in .env file");
  }

  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const wallet = new ethers.Wallet(privateKey, provider);
  
  console.log("\nDeploying with account:", wallet.address);
  const balance = await provider.getBalance(wallet.address);
  console.log("Account balance:", ethers.formatEther(balance), "ETH");
  
  // Get current nonce to ensure proper sequencing
  let currentNonce = await provider.getTransactionCount(wallet.address, "pending");
  console.log("Starting nonce:", currentNonce);

  // Load compiled contract artifacts
  // These would be generated by Foundry (forge build) or solc
  const artifactsPath = path.join(__dirname, "../out");
  
  // Try to load from Foundry output first, fallback to hardhat artifacts
  let simpleStorageV1Abi: any;
  let simpleStorageV1Bytecode: string;
  let proxyAbi: any;
  let proxyBytecode: string;

  try {
    // Try Foundry format first
    const v1Artifact = JSON.parse(
      fs.readFileSync(path.join(artifactsPath, "SimpleStorageV1.sol/SimpleStorageV1.json"), "utf8")
    );
    simpleStorageV1Abi = v1Artifact.abi;
    simpleStorageV1Bytecode = v1Artifact.bytecode.object;
    
    const proxyArtifact = JSON.parse(
      fs.readFileSync(path.join(artifactsPath, "Proxy.sol/Proxy.json"), "utf8")
    );
    proxyAbi = proxyArtifact.abi;
    proxyBytecode = proxyArtifact.bytecode.object;
  } catch (e) {
    // Fallback to Hardhat artifacts
    try {
      const v1Artifact = JSON.parse(
        fs.readFileSync(path.join(__dirname, "../artifacts/contracts/SimpleStorageV1.sol/SimpleStorageV1.json"), "utf8")
      );
      simpleStorageV1Abi = v1Artifact.abi;
      simpleStorageV1Bytecode = v1Artifact.bytecode;
      
      const proxyArtifact = JSON.parse(
        fs.readFileSync(path.join(__dirname, "../artifacts/contracts/Proxy.sol/Proxy.json"), "utf8")
      );
      proxyAbi = proxyArtifact.abi;
      proxyBytecode = proxyArtifact.bytecode;
    } catch (e2) {
      throw new Error("Could not find compiled contracts. Please run 'forge build' or 'hardhat compile' first.");
    }
  }

  // Step 1: Deploy V1 Implementation
  console.log("\n" + "=".repeat(60));
  console.log("STEP 1: Deploying SimpleStorageV1 Implementation");
  console.log("=".repeat(60));
  
  const SimpleStorageV1Factory = new ethers.ContractFactory(
    simpleStorageV1Abi,
    simpleStorageV1Bytecode,
    wallet
  );
  
  console.log("Deploying V1 (nonce:", currentNonce, ")...");
  const implementationV1 = await SimpleStorageV1Factory.deploy();
  const deployTx = implementationV1.deploymentTransaction();
  if (deployTx) {
    console.log("Deployment TX submitted:", deployTx.hash);
    console.log("Waiting for transaction to be mined...");
    await deployTx.wait(1); // Wait for 1 confirmation
  }
  await implementationV1.waitForDeployment();
  const implementationV1Address = await implementationV1.getAddress();
  
  console.log("✅ Implementation V1 deployed to:", implementationV1Address);
  
  // Wait a bit and get fresh nonce after V1 is confirmed
  await new Promise(resolve => setTimeout(resolve, 500)); // Small delay

  // Step 2: Prepare initialization data
  console.log("\n" + "=".repeat(60));
  console.log("STEP 2: Preparing Initialization Data");
  console.log("=".repeat(60));
  
  const initialValue = 100;
  const initialString = "Hello from V1";
  
  const iface = new ethers.Interface(simpleStorageV1Abi);
  const initializeData = iface.encodeFunctionData("initialize", [initialValue, initialString]);
  
  console.log("Initial values:");
  console.log("  - storedValue:", initialValue);
  console.log("  - storedString:", initialString);
  console.log("  - owner:", wallet.address);

  // Step 3: Deploy Proxy
  console.log("\n" + "=".repeat(60));
  console.log("STEP 3: Deploying Proxy Contract");
  console.log("=".repeat(60));
  console.log("The Proxy uses:");
  console.log("  - delegatecall to forward calls to implementation");
  console.log("  - Assembly code for storage operations");
  console.log("  - EIP-1967 storage slots");
  
  const ProxyFactory = new ethers.ContractFactory(
    proxyAbi,
    proxyBytecode,
    wallet
  );
  
  // Get fresh nonce before deploying proxy (after V1 is confirmed)
  currentNonce = await provider.getTransactionCount(wallet.address, "latest");
  console.log("Deploying Proxy (nonce:", currentNonce, ")...");
  
  const proxy = await ProxyFactory.deploy(
    implementationV1Address,
    initializeData,
    wallet.address // admin
  );
  const proxyDeployTx = proxy.deploymentTransaction();
  if (proxyDeployTx) {
    console.log("Proxy deployment TX submitted:", proxyDeployTx.hash);
    console.log("Waiting for transaction to be mined...");
    await proxyDeployTx.wait(1); // Wait for 1 confirmation
  }
  await proxy.waitForDeployment();
  const proxyAddress = await proxy.getAddress();
  
  console.log("✅ Proxy deployed to:", proxyAddress);

  // Step 4: Verify deployment
  console.log("\n" + "=".repeat(60));
  console.log("STEP 4: Verifying Deployment");
  console.log("=".repeat(60));
  
  const proxyContract = new ethers.Contract(proxyAddress, simpleStorageV1Abi, wallet);
  
  const version = await proxyContract.getVersion();
  const storedValue = await proxyContract.getValue();
  const storedString = await proxyContract.getString();
  const owner = await proxyContract.owner();
  
  console.log("\n✅ Contract State (via proxy):");
  console.log("  Version:", version.toString());
  console.log("  Stored Value:", storedValue.toString());
  console.log("  Stored String:", storedString);
  console.log("  Owner:", owner);

  // Save deployment info
  console.log("\n" + "=".repeat(60));
  console.log("=== Save this information ===");
  console.log("=".repeat(60));
  console.log("PROXY_ADDRESS=" + proxyAddress);
  console.log("IMPLEMENTATION_V1_ADDRESS=" + implementationV1Address);
  if (proxyDeployTx) {
    console.log("DEPLOYMENT_TX_HASH=" + proxyDeployTx.hash);
  }
  console.log("ADMIN_ADDRESS=" + wallet.address);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
