// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Storage$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Storage";
  readonly sourceName: "contracts/Storage.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"newNumber","type":"uint256"}],"name":"NumberStored","type":"event"},{"inputs":[{"internalType":"uint256","name":"_number","type":"uint256"}],"name":"setNumber","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"storedNumber","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b5060df80601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106030575f3560e01c806309ce9ccb1460345780633fb5c1cb146048575b5f5ffd5b5f5460405190815260200160405180910390f35b605760533660046093565b6059565b005b5f8190556040518181527f3564ffb2fd8f93d7b0e9d1173ffdff5ee9775d860bfe82eaca0d0dbe07c8b6349060200160405180910390a150565b5f6020828403121560a2575f5ffd5b503591905056fea26469706673582212205459bdb95e5129eb52e1831f584eeb2db42635fba012e71c5af9b6682819c8b664736f6c634300081c0033";
  readonly deployedBytecode: "0x6080604052348015600e575f5ffd5b50600436106030575f3560e01c806309ce9ccb1460345780633fb5c1cb146048575b5f5ffd5b5f5460405190815260200160405180910390f35b605760533660046093565b6059565b005b5f8190556040518181527f3564ffb2fd8f93d7b0e9d1173ffdff5ee9775d860bfe82eaca0d0dbe07c8b6349060200160405180910390a150565b5f6020828403121560a2575f5ffd5b503591905056fea26469706673582212205459bdb95e5129eb52e1831f584eeb2db42635fba012e71c5af9b6682819c8b664736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Storage.sol";
  readonly buildInfoId: "solc-0_8_28-8ddba8047c9e320b1af436453382847ffaafb919";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Storage"]: Storage$Type;
    ["contracts/Storage.sol:Storage"]: Storage$Type;
  }
}